management:
  server:
    port: 9000
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
server:
  shutdown: graceful
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: path-route
          uri: ${USER_SERVICE_URL:http://user-service-url:8080}
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}