apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: local
namePrefix: local-

resources:
  - ../../base

components:
  - ../../components/postgres

patchesStrategicMerge:
  - user-service/hpa-patch.yaml
  - api-gateway/ingress-patch.yaml

patchesJson6902:
  - target:
      kind: Deployment
      name: user-service-deployment
      group: apps
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m

configMapGenerator:
  - name: us-config
    envs:
      - user-service/config/config.properties
  - name: gateway-config
    envs:
      - api-gateway/config/config.properties

secretGenerator:
  - name: us-secrets
    envs:
      - user-service/config/secret.properties